"""Args in the script: a generated copy of a runbook workflow with its args embedded.

    uv run embed_workflow.py lesson-args <book> --lessons g10m8s1-1,g10m8s2-1,… [--out FILE] [--args-out A.json]
    uv run embed_workflow.py embed --script runbook/<name>.workflow.js --args A.json [--out FILE] [--tag T]
    uv run embed_workflow.py verify FILE
    uv run embed_workflow.py args FILE            # print the args a generated script carries

WHY (decision of 2026-09-26, the orchestrator under Samuel's standing "quality over cost" rule; Q1,
option A). A workflow's args are typed into the Workflow tool call, and two stages cannot be made
small by reference: S2–S4 (lesson.workflow.js), whose deterministic checks read every item's text
inside the script, and S5 final (misconceptions.workflow.js), whose script attaches every distractor
and carries every draft entry. For those, the builder writes a COPY of the runbook script with the
args embedded, and the operator runs it with `Workflow({scriptPath: <the copy>})` and NO args. Nothing
about the stage changes: the prompts, the checks, the blind rules and the cost are the runbook
script's own, byte for byte, because the copy is the runbook script with one line replaced.

THE COPY. `export const meta = {…}` stays first and unchanged (the meter keys on meta.name). The
runbook script's one line

    const ARGS = typeof args === 'string' ? (args ? JSON.parse(args) : {}) : (args || {})

becomes a block that (1) records EMBEDDED = {source, source_sha256, args_sha256, generated_sha256,
generator}, (2) refuses to run if it is given args (a copy never mixes two inputs), and (3) sets
ARGS to the embedded args plus `embedded: EMBEDDED`. Every workflow this can copy echoes
`ARGS.embedded` in its return value, so a saved run says which script ran: the runbook script's sha256
and the copy's. `generated_sha256` is the sha256 of the copy with that one value written as 64 zeros
(a file cannot hold its own hash); `verify` recomputes it. The downstream readers accept a run from a
copy exactly as a run from the runbook script: the return value is the same, plus `embedded`.

WHERE. Copies go under work/<book>/packets/embedded/ (gitignored, derived, regenerable from the
same inputs). A copy holds the whole packet — for S2–S4 that is every item's book solution and
printed answer and the lesson's teacher-only notes, as the args always did; no prompt names the
copy, and the same text is already on disk in work/<book>/blocks.jsonl. Resume a stopped run with
the SAME copy: regenerating it with different inputs changes its hash and misses the cache.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ARGS_LINE = "const ARGS = typeof args === 'string' ? (args ? JSON.parse(args) : {}) : (args || {})"
ZERO = "0" * 64
GENERATOR = "services/extraction/embed_workflow.py v1"
EMBEDDED_RE = re.compile(r"^const EMBEDDED = (\{.*\})$", re.M)
ARGS_RE = re.compile(r"^const EMBEDDED_ARGS = (.*)$", re.M)


class EmbedError(Exception):
    pass


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def _dumps(v) -> str:
    return json.dumps(v, ensure_ascii=False, separators=(",", ":"))


def _rel(p: Path) -> str:
    try:
        return str(Path(p).resolve().relative_to(HERE))
    except ValueError:
        return str(p)


def generate(source: Path, args: dict) -> str:
    """The text of the copy: `source` with its args line replaced by the embedded args."""
    src = Path(source).read_text()
    if not src.startswith("export const meta = "):
        raise EmbedError(f"{source}: does not start with `export const meta = …`")
    if src.count(ARGS_LINE) != 1:
        raise EmbedError(f"{source}: the args line occurs {src.count(ARGS_LINE)} time(s), not once")
    if "ARGS.embedded" not in src:
        raise EmbedError(f"{source}: does not echo ARGS.embedded in its return value, so a run of the copy "
                         "could not say which script ran")
    if not isinstance(args, dict) or not args:
        raise EmbedError("the args to embed must be a non-empty JSON object")
    if "embedded" in args:
        raise EmbedError("the args already carry `embedded` (they come from a copy): use the builder's own output")
    args_json = _dumps(args)
    info = {"source": _rel(source), "source_sha256": _sha(src), "args_sha256": _sha(args_json),
            "generated_sha256": ZERO, "generator": GENERATOR}
    block = "\n".join([
        f"// ---- EMBEDDED ARGS: generated by {GENERATOR} from {info['source']}. Do not edit: regenerate.",
        "// Run this file with the Workflow tool (scriptPath) and NO args. `generated_sha256` is the sha256 of",
        "// this whole file with that one value written as 64 zeros (`embed_workflow.py verify <file>`).",
        f"const EMBEDDED = {_dumps(info)}",
        "if (!(args === undefined || args === null || args === '' ||",
        "    (typeof args === 'object' && !Array.isArray(args) && Object.keys(args).length === 0))) {",
        "  throw new Error('this generated script carries its own args (embed_workflow.py): run it with no args')",
        "}",
        f"const EMBEDDED_ARGS = {args_json}",
        "const ARGS = Object.assign(EMBEDDED_ARGS, { embedded: EMBEDDED })",
    ])
    text = src.replace(ARGS_LINE, block)
    return _set_hash(text, _sha(text))


def _set_hash(text: str, h: str) -> str:
    m = EMBEDDED_RE.search(text)
    info = json.loads(m.group(1))
    info["generated_sha256"] = h
    return text[:m.start(1)] + _dumps(info) + text[m.end(1):]


def embedded_info(text: str) -> dict:
    m = EMBEDDED_RE.search(text)
    if not m:
        raise EmbedError("not a generated script: no `const EMBEDDED = {…}` line")
    return json.loads(m.group(1))


def read_args(path: Path) -> dict:
    """The args a copy carries (what the runbook script would have been given)."""
    m = ARGS_RE.search(Path(path).read_text())
    if not m:
        raise EmbedError(f"{path}: no `const EMBEDDED_ARGS = …` line")
    return json.loads(m.group(1))


def verify(path: Path, source: Path | None = None) -> list[str]:
    """Problems with a copy (empty: it is what its EMBEDDED block says)."""
    text = Path(path).read_text()
    info = embedded_info(text)
    out = []
    if _sha(_set_hash(text, ZERO)) != info["generated_sha256"]:
        out.append(f"{path}: generated_sha256 does not match the file (it was edited after it was written)")
    if _sha(_dumps(read_args(path))) != info["args_sha256"]:
        out.append(f"{path}: args_sha256 does not match the embedded args")
    src = Path(source) if source else HERE / info["source"]
    if src.exists():
        if _sha(src.read_text()) != info["source_sha256"]:
            out.append(f"{path}: {info['source']} has changed since this copy was generated (source_sha256 differs); "
                       "a copy runs the script as it was — regenerate it to run today's")
        elif generate(src, read_args(path)) != text:
            out.append(f"{path}: is not what {info['source']} and its args generate")
    return out


def write(source: Path, args: dict, out: Path) -> dict:
    """Write the copy; return its EMBEDDED block plus its path and size (the sidecar's content)."""
    text = generate(source, args)
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    info = dict(embedded_info(text), script=str(out.resolve()), bytes=len(text.encode()),
                args_bytes=len(_dumps(args).encode()))
    out.with_suffix(".json").write_text(json.dumps(info, indent=1) + "\n")
    return info


def default_out(book: str, name: str, tag: str) -> Path:
    return HERE / "work" / book / "packets" / "embedded" / f"{name}.{tag}.workflow.js"


def summary(info: dict) -> str:
    return (f"generated {info['script']} ({info['bytes']} bytes; args {info['args_bytes']} bytes embedded) — "
            f"run it with Workflow scriptPath and NO args. source {info['source']} sha256 {info['source_sha256'][:12]}…, "
            f"generated sha256 {info['generated_sha256'][:12]}…")


# ---------------------------------------------------------------- commands
def cmd_lesson_args(a) -> int:
    """S2–S4: `assemble_objectives.py lesson-args`, written as a copy of lesson.workflow.js."""
    import assemble_objectives as ao
    book = ao._book(a)
    p, manifest, blocks, maths = ao._inputs(book, a)
    lessons = [s.strip() for s in a.lessons.split(",") if s.strip()]
    args = ao.lesson_args(book, manifest, blocks, maths, p["objectives"], lessons, p["work"])
    if a.args_out:
        Path(a.args_out).write_text(json.dumps(args, ensure_ascii=False, indent=1) + "\n")
    tag = lessons[0] if len(lessons) == 1 else f"{lessons[0]}..{lessons[-1]}"
    out = Path(a.out) if a.out else default_out(book.book, "lesson", tag)
    info = write(HERE / "runbook" / "lesson.workflow.js", args, out)
    print(f"lesson args: {len(args['lessons'])} lesson(s), {sum(len(l['items']) for l in args['lessons'])} exercise "
          f"item(s); " + summary(info))
    return 0


def cmd_embed(a) -> int:
    args = json.loads(Path(a.args).read_text())
    src = Path(a.script)
    book = (args.get("book") or {}).get("book") if isinstance(args.get("book"), dict) else args.get("book")
    out = Path(a.out) if a.out else default_out(book or "unknown-book", src.name.split(".")[0], a.tag or "run")
    print(summary(write(src, args, out)))
    return 0


def cmd_verify(a) -> int:
    problems = verify(Path(a.file))
    for p in problems:
        print(f"  x {p}", file=sys.stderr)
    info = embedded_info(Path(a.file).read_text())
    print(f"{a.file}: {'OK' if not problems else f'{len(problems)} problem(s)'} — source {info['source']}, "
          f"generated_sha256 {info['generated_sha256']}")
    return 1 if problems else 0


def cmd_args(a) -> int:
    print(json.dumps(read_args(Path(a.file)), ensure_ascii=False, indent=1))
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("lesson-args", help="S2–S4 args (assemble_objectives.py lesson-args) as a copy of lesson.workflow.js")
    p.add_argument("book")
    for opt in ("--book-config", "--blocks", "--manifest", "--maths", "--objectives-dir", "--runs-dir"):
        p.add_argument(opt)
    p.add_argument("--lessons", required=True)
    p.add_argument("--out", help="the copy (default work/<book>/packets/embedded/lesson.<lessons>.workflow.js)")
    p.add_argument("--args-out", help="also write the args themselves here (for reading; not for pasting)")
    p.set_defaults(fn=cmd_lesson_args)
    p = sub.add_parser("embed", help="any builder's args file as a copy of its workflow")
    p.add_argument("--script", required=True)
    p.add_argument("--args", required=True)
    p.add_argument("--out")
    p.add_argument("--tag")
    p.set_defaults(fn=cmd_embed)
    p = sub.add_parser("verify", help="check a copy against its EMBEDDED block and its source script")
    p.add_argument("file")
    p.set_defaults(fn=cmd_verify)
    p = sub.add_parser("args", help="print the args a copy carries")
    p.add_argument("file")
    p.set_defaults(fn=cmd_args)
    a = ap.parse_args(argv)
    try:
        return a.fn(a)
    except EmbedError as e:
        print(f"embed_workflow: {e}", file=sys.stderr)
        return 2
    except Exception as e:  # noqa: BLE001 — assemble_objectives' StageError, reported the same way
        if type(e).__name__ == "StageError":
            print(f"embed_workflow: {e}", file=sys.stderr)
            return 2
        raise


if __name__ == "__main__":
    sys.exit(main())
