import Script from "next/script";

import { gaBootstrap, type ConsentSurface } from "@/lib/ga";
import { GA_MEASUREMENT_ID } from "@/lib/env";

/**
 * The GA4 tag's **only insertion point in this codebase** (ADR-0016 §2,
 * contracts/analytics.md, FR-2504, FR-2505, SC-114).
 *
 * Rendered from the student `layout.tsx`, inside the branch that is skipped on
 * the console build. There is no second place a tag can be added without this
 * file being edited, which is what makes "never loaded on the console" a
 * property of the tree rather than a rule somebody follows.
 *
 * ---------------------------------------------------------------------------
 * WHY THE DOMAIN LIVES HERE AND NOT IN `lib/ga.ts`
 * ---------------------------------------------------------------------------
 * This is a **server** component: its module is never shipped to a browser, so
 * `googletagmanager.com` appears in no client bundle on either build. `lib/ga.ts`
 * is bundled for the client (client components call `track`), so keeping the
 * loader URL out of it is what lets `grep -r googletagmanager .next-admin/static`
 * answer zero rather than answer "the string is there but never runs".
 *
 * ---------------------------------------------------------------------------
 * ASYNC, AND NOTHING BEHIND IT (FR-2505)
 * ---------------------------------------------------------------------------
 * `next/script` with `afterInteractive` emits `async`, and neither tag is
 * awaited by anything. If gtag.js never arrives — ad blocker, school proxy,
 * blocked domain, unset id — `window.gtag` stays the tiny inline shim that
 * pushes to an array nobody reads, `track()` finds no `gtag` and no-ops, and
 * every page, lesson, upload and dashboard renders exactly as before. The
 * inline bootstrap is a `dataLayer` queue, so the ORDER of its pushes is what
 * fixes consent-before-config, not the order in which the two tags load.
 *
 * ---------------------------------------------------------------------------
 * THE SURFACE IS RESOLVED FROM THE PRINCIPAL, NOT THE PATH — AND WHY
 * ---------------------------------------------------------------------------
 * contracts/analytics.md names the cookieless surface by path (`/student`,
 * `/dashboard`, `/spine`). A root layout in the App Router cannot read the
 * pathname, and the alternatives — a client component that reads
 * `usePathname()`, or a header set in `proxy.ts` — both decide consent after
 * the first `dataLayer` push, which is the one thing that must not happen.
 *
 * So the shell asks a question it *can* answer: **is there a signed-in student
 * on this request?** Every one of the three named surfaces requires one, so a
 * visitor on those paths is always caught. The difference is in the other
 * direction: a signed-in student reading the landing page is treated as the
 * authenticated surface and gets no `_ga` cookie either. That is a STRICTER
 * reading of the contract, never a looser one, and the failure direction of an
 * approximation about a minor's cookie should be the denying one.
 *
 * Soft client navigation cannot move a visitor between the two regimes in the
 * granting direction: signing in replaces the document (`/signin` redirects),
 * and the layout is `force-dynamic`, so consent is re-decided per document.
 */
export function GaScript({ signedIn }: { signedIn: boolean }) {
  if (!GA_MEASUREMENT_ID) return null;

  const surface: ConsentSurface = signedIn ? "student-auth" : "public";

  return (
    <>
      {/* Consent defaults, `js`, `config`, one stripped page_view — in that
          order, generated by lib/ga.ts so no caller can reorder them. */}
      <Script id="ga-bootstrap" strategy="afterInteractive">
        {gaBootstrap(GA_MEASUREMENT_ID, surface)}
      </Script>
      <Script
        id="ga-loader"
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(
          GA_MEASUREMENT_ID
        )}`}
      />
    </>
  );
}
