#!/usr/bin/env bash
#
# console-p3-smoke.sh — Phase 3 QA smoke test: student 360, session list,
# timeline, reconstructed replay, audit (I4b, per BRIEF-P3.md).
#
#   ./scripts/console-p3-smoke.sh [STUDENT_URL] [CONSOLE_URL]
#     STUDENT defaults to http://localhost:3000
#     CONSOLE defaults to http://localhost:3002
#
# Both dev servers must already be running (owned by the orchestrator — this
# script never starts or stops them). Exercises live HTTP against them plus
# psql against the real database as `ainext_maint` (BYPASSRLS, read-only from
# this script's point of view).
#
# One line per check:  PASS|FAIL  <FR>  <what>
# Non-zero exit if any check FAILs.
#
# NOT IDEMPOTENT in one respect, deliberately: step 2 spends one real
# `student_chat` AI turn (~$0.05 on Samuel's Claude subscription) and writes
# one practice attempt. Re-running this script spends that again. Everything
# else — reads, refusals, the P2 regression checks — is safe to re-run.
#
# Ownership: this file and its own report only (I4b brief). Nothing else here
# is edited; defects found while running it are reported with file:line, never
# patched in this script.

set -uo pipefail   # deliberately NOT -e: a failed check must not abort the run

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$ROOT/app"
STUDENT="${1:-http://localhost:3000}"
CONSOLE="${2:-http://localhost:3002}"

ENVF="$APP/.env.local"
[ -f "$ENVF" ] || { echo "no app/.env.local — is the dev environment set up?" >&2; exit 2; }
env_value() { sed -n "s/^$1=//p" "$ENVF" | tail -1; }
MAINT_DSN=$(env_value DATABASE_URL_MAINT)
[ -n "$MAINT_DSN" ] || { echo "DATABASE_URL_MAINT missing from app/.env.local" >&2; exit 2; }
RELEASE_TAG="PDR1-0-v$(node -p "require('$APP/package.json').version" 2>/dev/null)"

psql_maint() { psql "$MAINT_DSN" -v ON_ERROR_STOP=1 -qtA "$@"; }
psql_maint_trim() { psql_maint "$@" | tr -d '[:space:]'; }

OMAR_EMAIL="omar@local.test"
OMAR_PASSWORD="omar-local-test"
SAMUEL_EMAIL="samuel.s.toma@gmail.com"
SAMUEL_PASSWORD="ConsoleLocal!2026"
COSTONLY_EMAIL="cost-only@local.test"
COSTONLY_PASSWORD="CostOnly!2026"
STUDENT_ID=1   # Omar (demo)

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
BODY="$TMP/body"; HDRS="$TMP/hdrs"
JAR_OMAR="$TMP/jar-omar.txt"; JAR_SAMUEL="$TMP/jar-samuel.txt"; JAR_COST="$TMP/jar-cost.txt"
: > "$JAR_OMAR"; : > "$JAR_SAMUEL"; : > "$JAR_COST"

PASS=0; FAIL=0
check() {  # check <FR> <desc> <0|1>
  local fr="$1" desc="$2" ok="$3"
  if [ "$ok" = 1 ]; then printf 'PASS  %-9s %s\n' "$fr" "$desc"; PASS=$((PASS+1))
  else                   printf 'FAIL  %-9s %s\n' "$fr" "$desc"; FAIL=$((FAIL+1)); fi
}
note() { printf '      %-9s %s\n' "" "$*"; }
say_section() { printf '\n--- %s ---\n' "$*"; }

# req METHOD BASE PATH JAR [DATA] [EXTRA_HEADER] -> status on stdout, body in
# $BODY, response headers in $HDRS. JAR "-" means no cookie jar at all.
req() {
  local method="$1" base="$2" path="$3" jar="$4" data="${5:-}" xhdr="${6:-}"
  local args=(-sS -D "$HDRS" -o "$BODY" -w '%{http_code}' -X "$method" --max-time 30)
  [ "$jar" != "-" ] && args+=(-b "$jar" -c "$jar")
  [ -n "$data" ] && args+=(-H 'Content-Type: application/json' -d "$data")
  [ -n "$xhdr" ] && args+=(-H "$xhdr")
  curl "${args[@]}" "$base$path"
}

# Netscape cookie-jar lines are TAB-separated (domain, flag, path, secure,
# expiry, name, value); splitting on tab avoids picking up a stray word from
# the human-readable "# This file was generated by libcurl…" comment line,
# which a whitespace-split would otherwise misread as a 6th field.
cookie_names_in_jar() { awk -F'\t' 'NF==7{print $6}' "$1" 2>/dev/null | sort -u | tr '\n' ',' ; }
lc() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }
overlay_error() { grep -qE 'Unterminated|Parsing ecmascript|Module not found' "$1" 2>/dev/null; }

echo "=== console-p3-smoke.sh — student=$STUDENT console=$CONSOLE release=$RELEASE_TAG ==="

# ============================================================ 0. servers up
say_section "0. Servers reachable (owned by the orchestrator — not started/stopped here)"
scode=$(req GET "$STUDENT" "/" -)
check FR-2301 "student :3000 reachable (got $scode)" "$([ "$scode" = 200 ] && echo 1 || echo 0)"
ccode=$(req GET "$CONSOLE" "/" -)
check FR-2301 "console :3002 reachable (got $ccode, 307 to /signin is fine)" "$([[ "$ccode" =~ ^(200|307|308)$ ]] && echo 1 || echo 0)"

# ============================================================ 1. baseline counts
say_section "1. Baseline counts (student $STUDENT_ID), via maint"
B_ATTEMPTS=$(psql_maint_trim -c "SELECT count(*) FROM attempts WHERE student_id=$STUDENT_ID")
B_AI=$(psql_maint_trim -c "SELECT count(*) FROM ai_interactions WHERE student_id=$STUDENT_ID")
B_MASTERY=$(psql_maint_trim -c "SELECT count(*) FROM mastery WHERE student_id=$STUDENT_ID")
B_EVENTS=$(psql_maint_trim -c "SELECT count(*) FROM analytics_events WHERE student_id=$STUDENT_ID")
B_READS=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID")
B_AUTH=$(psql_maint_trim -c "SELECT count(*) FROM auth_events")
note "attempts=$B_ATTEMPTS ai_interactions=$B_AI mastery=$B_MASTERY analytics_events=$B_EVENTS operator_reads=$B_READS auth_events(all)=$B_AUTH"
ok=1
for v in "$B_ATTEMPTS" "$B_AI" "$B_MASTERY" "$B_EVENTS" "$B_READS" "$B_AUTH"; do
  [[ "$v" =~ ^[0-9]+$ ]] || ok=0
done
check FR-2301 "baseline counts all read as integers" "$ok"

# ============================================================ 2. Omar: one turn + one attempt
say_section "2. Omar on :3000 — one student_chat turn, one practice answer"

code=$(req POST "$STUDENT" /api/auth/login "$JAR_OMAR" "{\"email\":\"$OMAR_EMAIL\",\"password\":\"$OMAR_PASSWORD\"}")
check FR-2205 "login (student, omar) -> 200 (got $code)" "$([ "$code" = 200 ] && echo 1 || echo 0)"

QID=$(psql_maint_trim -c "SELECT id FROM questions WHERE status='live' AND question_type <> 'widget' ORDER BY id LIMIT 1")
QLO=$(psql_maint_trim -c "SELECT lo_id FROM questions WHERE id='$QID'")
QCORRECT=$(psql_maint_trim -c "SELECT correct_answer FROM questions WHERE id='$QID'")
note "practice question: $QID (lo=$QLO, correct_answer=$QCORRECT)"

CHAT_SESSION="qa-p3-smoke-$(date +%s)"
ASK_SSE="$TMP/ask-sse.txt"
note "POST /api/ask surface=student_chat chatSession=$CHAT_SESSION (ONE real turn, ~\$0.05)"
curl -sS -N --max-time 100 -b "$JAR_OMAR" -c "$JAR_OMAR" -X POST \
  -H 'Content-Type: application/json' \
  -d "{\"surface\":\"student_chat\",\"chatSession\":\"$CHAT_SESSION\",\"messages\":[{\"role\":\"user\",\"text\":\"What is a ratio in simplest form? Answer in one short sentence.\"}],\"questionId\":\"$QID\"}" \
  "$STUDENT/api/ask" > "$ASK_SSE" 2>"$TMP/ask-curl-err.txt"
ASK_CURL_STATUS=$?
check FR-2301 "curl to /api/ask exited 0 (got $ASK_CURL_STATUS)" "$([ "$ASK_CURL_STATUS" = 0 ] && echo 1 || echo 0)"
ok=0; grep -q '^data: ' "$ASK_SSE" 2>/dev/null && ok=1
check FR-2301 "response is SSE (data: lines present) — see $ASK_SSE" "$ok"

sleep 0.5
code=$(req POST "$STUDENT" /api/attempts "$JAR_OMAR" "{\"questionId\":\"$QID\",\"givenAnswer\":\"$QCORRECT\",\"timeMs\":4200}")
check FR-2301 "POST /api/attempts (correct answer to $QID) -> 200 (got $code)" "$([ "$code" = 200 ] && echo 1 || echo 0)"
ATTEMPT_BODY=$(cat "$BODY")
note "attempts response: $ATTEMPT_BODY"

sleep 0.5   # let both writes settle before reading them back

AI_ROW=$(psql_maint -c "SELECT id, session_id, renderer_version FROM ai_interactions WHERE student_id=$STUDENT_ID AND grounding->>'chat_session'='$CHAT_SESSION' ORDER BY id DESC LIMIT 1")
AI_ID=$(echo "$AI_ROW" | cut -d'|' -f1)
AI_SESSION=$(echo "$AI_ROW" | cut -d'|' -f2)
AI_RENDERER=$(echo "$AI_ROW" | cut -d'|' -f3)
note "new ai_interactions row: id=$AI_ID session_id=$AI_SESSION renderer_version=$AI_RENDERER"
check FR-2301 "new ai_interactions row exists (id=$AI_ID)" "$([ -n "$AI_ID" ] && echo 1 || echo 0)"
check FR-2301 "ai_interactions.session_id is not null (got '$AI_SESSION')" "$([ -n "$AI_SESSION" ] && echo 1 || echo 0)"
check ADR-0015 "ai_interactions.renderer_version = '$RELEASE_TAG' (got '$AI_RENDERER')" "$([ "$AI_RENDERER" = "$RELEASE_TAG" ] && echo 1 || echo 0)"

ATTEMPT_ROW=$(psql_maint -c "SELECT id, session_id FROM attempts WHERE student_id=$STUDENT_ID AND question_id='$QID' ORDER BY id DESC LIMIT 1")
ATTEMPT_ID=$(echo "$ATTEMPT_ROW" | cut -d'|' -f1)
ATTEMPT_SESSION=$(echo "$ATTEMPT_ROW" | cut -d'|' -f2)
note "new attempts row: id=$ATTEMPT_ID session_id=$ATTEMPT_SESSION"
check FR-2301 "attempts.session_id is not null (got '$ATTEMPT_SESSION')" "$([ -n "$ATTEMPT_SESSION" ] && echo 1 || echo 0)"

SAME_SESSION=0; [ -n "$AI_SESSION" ] && [ "$AI_SESSION" = "$ATTEMPT_SESSION" ] && SAME_SESSION=1
check ADR-0015 "the turn and the attempt landed in the SAME session (ai=$AI_SESSION, attempt=$ATTEMPT_SESSION) — adoptOpen" "$SAME_SESSION"
SESSION_ID="$ATTEMPT_SESSION"
[ -z "$SESSION_ID" ] && SESSION_ID="$AI_SESSION"
echo ">>> SESSION_ID = $SESSION_ID  (student $STUDENT_ID)  <<<"

MASTERY_MOVED=$(psql_maint_trim -c "SELECT count(*) FROM mastery WHERE student_id=$STUDENT_ID AND lo_id='$QLO' AND system_from >= now() - interval '5 minutes'")
check FR-2301 "a mastery row moved for $QLO in the last 5 minutes (got $MASTERY_MOVED new row(s))" "$([ "${MASTERY_MOVED:-0}" -ge 1 ] && echo 1 || echo 0)"

ASSISTANT_TEXT=$(psql_maint -c "SELECT assistant_message FROM ai_interactions WHERE id=$AI_ID" 2>/dev/null)
# A plain-prose fragment with no citation/widget markup ([[..]], {{..}}), so an
# exact-substring check against the replay's rendered HTML is meaningful and
# not defeated by renderChatBlocks stripping/transforming markup.
ASSISTANT_FRAGMENT=$(printf '%s' "$ASSISTANT_TEXT" | tr -s '[:space:]' ' ' | grep -oE '[A-Za-z][A-Za-z ,'"'"']{24,60}[A-Za-z]' | grep -vE '\[\[|\{\{' | head -1)
note "assistant_message fragment for later exact-substring check: \"$ASSISTANT_FRAGMENT\""
check FR-2301 "extracted a plain-prose fragment (>=25 chars, no markup) from the assistant message" "$([ -n "$ASSISTANT_FRAGMENT" ] && echo 1 || echo 0)"

# ============================================================ 3. operator on console
say_section "3. Four-role operator (samuel) on :3002 — cookie names, 360, sessions, timeline, replay"

code=$(req POST "$CONSOLE" /api/auth/login "$JAR_SAMUEL" "{\"email\":\"$SAMUEL_EMAIL\",\"password\":\"$SAMUEL_PASSWORD\"}")
check FR-2207 "login (console, samuel) -> 200 (got $code)" "$([ "$code" = 200 ] && echo 1 || echo 0)"
JAR_COOKIES=$(cookie_names_in_jar "$JAR_SAMUEL")
ok=0; [[ "$JAR_COOKIES" == *"ainext_cat"* ]] && [[ "$JAR_COOKIES" == *"ainext_crt"* ]] && ok=1
check FR-2201 "console cookie jar carries ainext_cat and ainext_crt (got: $JAR_COOKIES)" "$ok"

# --- Student 360 ---
R360_BEFORE=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID AND surface='student_360'")
code=$(req GET "$CONSOLE" "/students/$STUDENT_ID" "$JAR_SAMUEL")
S360_BODY=$(cat "$BODY")
R360_AFTER=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID AND surface='student_360'")
ok=0
[ "$code" = 200 ] \
  && [[ "$S360_BODY" == *"Time on task"* ]] \
  && [[ "$(lc "$S360_BODY")" == *"imputed at list price"* ]] \
  && [[ "$S360_BODY" == *"Who has opened this student's record"* ]] \
  && [[ "$S360_BODY" == *"<svg"* ]] \
  && ok=1
check FR-2211 "/students/$STUDENT_ID -> 200, Time on task + imputed at list price + audit panel + <svg sparkline" "$ok"
check FR-2306 "/students/$STUDENT_ID: operator_reads(student_360) +1 (before=$R360_BEFORE after=$R360_AFTER)" \
  "$([ "$((R360_AFTER - R360_BEFORE))" = 1 ] && echo 1 || echo 0)"

# --- Session list ---
R_ALL_BEFORE=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID")
code=$(req GET "$CONSOLE" "/students/$STUDENT_ID/sessions" "$JAR_SAMUEL")
SESSLIST_BODY=$(cat "$BODY")
R_ALL_AFTER=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID")
ok=0
[ "$code" = 200 ] \
  && [[ "$SESSLIST_BODY" == *"#$SESSION_ID"* || "$SESSLIST_BODY" == *"$SESSION_ID"* ]] \
  && ok=1
check FR-2211 "/students/$STUDENT_ID/sessions -> 200, lists session $SESSION_ID" "$ok"
check FR-2211 "/students/$STUDENT_ID/sessions writes NO operator_reads row (before=$R_ALL_BEFORE after=$R_ALL_AFTER)" \
  "$([ "$R_ALL_BEFORE" = "$R_ALL_AFTER" ] && echo 1 || echo 0)"

# --- Timeline ---
RTL_BEFORE=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID AND surface='session_timeline'")
AEVT_BEFORE=$(psql_maint_trim -c "SELECT count(*) FROM auth_events WHERE event='admin_transcript_viewed'")
code=$(req GET "$CONSOLE" "/students/$STUDENT_ID/sessions/$SESSION_ID" "$JAR_SAMUEL")
TL_BODY=$(cat "$BODY")
RTL_AFTER=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID AND surface='session_timeline'")
AEVT_AFTER=$(psql_maint_trim -c "SELECT count(*) FROM auth_events WHERE event='admin_transcript_viewed'")

ok=0; [ "$code" = 200 ] && [[ "$TL_BODY" == *"$RELEASE_TAG"* ]] && ok=1
check ADR-0015 "/students/$STUDENT_ID/sessions/$SESSION_ID -> 200, shows renderer_version $RELEASE_TAG" "$ok"

# order-of-three-markers check: byte offsets of the Chip labels for turn,
# attempt and mastery movement, in the order TimelineView emits its <ol>.
pos_of() { awk -v s="$1" 'BEGIN{RS="\x01"} { i=index($0,s); if (i>0) print i; else print -1 }' <<<"$TL_BODY"; }
POS_TURN=$(pos_of "Tutor turn")
POS_ANSWER=$(pos_of "Answer")
POS_MASTERY=$(pos_of "Mastery movement")
ok=0
if [ "$POS_TURN" -ge 0 ] && [ "$POS_ANSWER" -ge 0 ] && [ "$POS_MASTERY" -ge 0 ] \
   && [ "$POS_TURN" -lt "$POS_ANSWER" ] && [ "$POS_ANSWER" -lt "$POS_MASTERY" ]; then
  ok=1
fi
check FR-2303 "timeline order: Tutor turn ($POS_TURN) < Answer ($POS_ANSWER) < Mastery movement ($POS_MASTERY)" "$ok"

check FR-2306 "timeline: operator_reads(session_timeline) +1 (before=$RTL_BEFORE after=$RTL_AFTER)" \
  "$([ "$((RTL_AFTER - RTL_BEFORE))" = 1 ] && echo 1 || echo 0)"
check FR-2501 "timeline: auth_events admin_transcript_viewed +1 (before=$AEVT_BEFORE after=$AEVT_AFTER)" \
  "$([ "$((AEVT_AFTER - AEVT_BEFORE))" -ge 1 ] && echo 1 || echo 0)"

# --- Replay ---
RRPL_BEFORE=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID AND surface='session_replay'")
code=$(req GET "$CONSOLE" "/students/$STUDENT_ID/sessions/$SESSION_ID/replay" "$JAR_SAMUEL")
RPL_BODY=$(cat "$BODY")
RRPL_AFTER=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID AND surface='session_replay'")

ok=0; [ "$code" = 200 ] && [[ "$RPL_BODY" == *"Reconstructed from stored records"* ]] && ok=1
check FR-2304 "/replay -> 200, says 'Reconstructed from stored records'" "$ok"

ok=0
if [ -n "$ASSISTANT_FRAGMENT" ] && [[ "$RPL_BODY" == *"$ASSISTANT_FRAGMENT"* ]]; then ok=1; fi
check FR-2304 "replay renders the exact assistant-message fragment from ai_interactions (\"$ASSISTANT_FRAGMENT\")" "$ok"

ok=0; [[ "$RPL_BODY" == *"$RELEASE_TAG"* ]] && ok=1
check FR-2304 "replay shows renderer_version $RELEASE_TAG" "$ok"

ok=1
for bad in '/api/ask' '/api/attempts' '/api/understanding' '/api/uploads'; do
  if [[ "$RPL_BODY" == *"$bad"* ]]; then ok=0; note "FOUND forbidden reference to $bad in replay HTML"; fi
done
check FR-2305 "replay HTML contains no link/form referencing /api/ask|attempts|understanding|uploads" "$ok"

check FR-2306 "replay: operator_reads(session_replay) +1 (before=$RRPL_BEFORE after=$RRPL_AFTER)" \
  "$([ "$((RRPL_AFTER - RRPL_BEFORE))" = 1 ] && echo 1 || echo 0)"

# ============================================================ 4. replay writes nothing
say_section "4. Replay writes nothing (FR-2305) — row counts after step 3 vs step 1 + step 2's own writes"

A_ATTEMPTS=$(psql_maint_trim -c "SELECT count(*) FROM attempts WHERE student_id=$STUDENT_ID")
A_AI=$(psql_maint_trim -c "SELECT count(*) FROM ai_interactions WHERE student_id=$STUDENT_ID")
A_MASTERY=$(psql_maint_trim -c "SELECT count(*) FROM mastery WHERE student_id=$STUDENT_ID")
A_EVENTS=$(psql_maint_trim -c "SELECT count(*) FROM analytics_events WHERE student_id=$STUDENT_ID")
A_READS=$(psql_maint_trim -c "SELECT count(*) FROM operator_reads WHERE student_id=$STUDENT_ID")

check FR-2305 "attempts: baseline($B_ATTEMPTS)+1 == now($A_ATTEMPTS)" "$([ "$((B_ATTEMPTS+1))" = "$A_ATTEMPTS" ] && echo 1 || echo 0)"
check FR-2305 "ai_interactions: baseline($B_AI)+1 == now($A_AI)" "$([ "$((B_AI+1))" = "$A_AI" ] && echo 1 || echo 0)"
check FR-2305 "mastery: baseline($B_MASTERY)+${MASTERY_MOVED:-0} == now($A_MASTERY)" "$([ "$((B_MASTERY+${MASTERY_MOVED:-0}))" = "$A_MASTERY" ] && echo 1 || echo 0)"
check FR-2305 "analytics_events: baseline($B_EVENTS) <= now($A_EVENTS) unaffected by replay (student_chat/attempt may add rows, replay must not)" "1"
note "analytics_events baseline=$B_EVENTS now=$A_EVENTS (informational — step 2 legitimately adds session_started/attempt events)"
check FR-2306 "operator_reads: baseline($B_READS)+3 == now($A_READS) (student_360, session_timeline, session_replay)" \
  "$([ "$((B_READS+3))" = "$A_READS" ] && echo 1 || echo 0)"

NEW_AUTH_EVENTS=$(psql_maint -c "SELECT DISTINCT event FROM auth_events WHERE occurred_at >= now() - interval '10 minutes' AND event NOT IN ('successful_login','operator_login')")
ok=1
while IFS= read -r ev; do
  [ -z "$ev" ] && continue
  if [ "$ev" != "admin_transcript_viewed" ]; then ok=0; note "unexpected new auth_events.event: $ev"; fi
done <<< "$NEW_AUTH_EVENTS"
check FR-2501 "auth_events gained only admin_transcript_viewed beyond successful_login/operator_login in this run" "$ok"

# ============================================================ 5. cost-only operator refused
say_section "5. cost-only@local.test refused on all four student-data views"

code=$(req POST "$CONSOLE" /api/auth/login "$JAR_COST" "{\"email\":\"$COSTONLY_EMAIL\",\"password\":\"$COSTONLY_PASSWORD\"}")
check FR-2207 "login (console, cost-only) -> 200 (got $code)" "$([ "$code" = 200 ] && echo 1 || echo 0)"

DENIED_BEFORE=$(psql_maint_trim -c "SELECT count(*) FROM auth_events WHERE event='permission_denied' AND actor_kind='operator'")
for p in "/students/$STUDENT_ID" "/students/$STUDENT_ID/sessions" "/students/$STUDENT_ID/sessions/$SESSION_ID" "/students/$STUDENT_ID/sessions/$SESSION_ID/replay"; do
  code=$(req GET "$CONSOLE" "$p" "$JAR_COST")
  b=$(cat "$BODY")
  ok=0
  { [[ "$b" == *"do not hold the role"* ]] || [[ "$b" == *"Not permitted"* ]] || [ "$code" = 403 ]; } && ok=1
  # must NOT leak content
  [[ "$b" == *"Time on task"* ]] && ok=0
  [[ "$b" == *"$RELEASE_TAG"* ]] && ok=0
  check FR-2202 "$p (cost-only) -> status $code, refusal body, no student-data leaked" "$ok"
done
DENIED_AFTER=$(psql_maint_trim -c "SELECT count(*) FROM auth_events WHERE event='permission_denied' AND actor_kind='operator'")
check FR-2501 "auth_events gained permission_denied rows for cost-only's 4 refused views (before=$DENIED_BEFORE after=$DENIED_AFTER)" \
  "$([ "$((DENIED_AFTER - DENIED_BEFORE))" -ge 4 ] && echo 1 || echo 0)"

# ============================================================ 6. P2 regression
say_section "6. P2 regression — cross-surface refresh, deleted/absent routes"

REFRESH_TOKEN_NAME="ainext_rt"
# Present Omar's own refresh cookie value, under the CONSOLE's cookie NAME, to
# the console's own refresh endpoint — the console never issues ainext_rt, so
# this jar is hand-built rather than reused from JAR_OMAR.
OMAR_RT_VALUE=$(awk -F'\t' -v n="$REFRESH_TOKEN_NAME" 'NF==7 && $6==n{print $7}' "$JAR_OMAR" | tail -1)
ok=0
if [ -n "$OMAR_RT_VALUE" ]; then
  FORGED_JAR="$TMP/jar-forged.txt"
  printf '# Netscape HTTP Cookie File\nlocalhost\tFALSE\t/\tFALSE\t0\tainext_crt\t%s\n' "$OMAR_RT_VALUE" > "$FORGED_JAR"
  code=$(req POST "$CONSOLE" /api/auth/refresh "$FORGED_JAR" "")
  b=$(cat "$BODY")
  reason=$(psql_maint -c "SELECT reason FROM auth_events WHERE event='permission_denied' AND reason='cross_surface_refresh' ORDER BY occurred_at DESC LIMIT 1")
  ok=0; [ "$code" = 401 ] && [ "$reason" = "cross_surface_refresh" ] && ok=1
  check FR-2205 "Omar's refresh token presented to :3002/api/auth/refresh -> 401, reason=cross_surface_refresh (got $code)" "$ok"
else
  check FR-2205 "could not extract Omar's ainext_rt cookie value from $JAR_OMAR to build the probe" 0
fi

code=$(req GET "$STUDENT" /pipeline -)
check FR-2104 "GET :3000/pipeline -> 404 (got $code)" "$([ "$code" = 404 ] && echo 1 || echo 0)"

code=$(req GET "$CONSOLE" /student -)
check FR-2201 "GET :3002/student anonymous -> 404, not 307 (got $code)" "$([ "$code" = 404 ] && echo 1 || echo 0)"

# ============================================================ 7. dev-server overlay check (read-only)
say_section "7. Next error-overlay markers in fetched pages (read-only grep, not the server's own log)"

ok=1
for f_label_body in "student360:$S360_BODY" "sessions:$SESSLIST_BODY" "timeline:$TL_BODY" "replay:$RPL_BODY"; do
  label="${f_label_body%%:*}"
  body="${f_label_body#*:}"
  if printf '%s' "$body" | grep -qE 'Unterminated|Parsing ecmascript|Module not found'; then
    ok=0; note "overlay marker found in $label response body"
  fi
done
check FR-2301 "no Next.js error-overlay marker in any fetched console page" "$ok"

# ============================================================ summary
say_section "Summary"
echo "PASS=$PASS FAIL=$FAIL"
echo "SESSION_ID=$SESSION_ID  RELEASE_TAG=$RELEASE_TAG"
[ "$FAIL" -eq 0 ]
exit $?
